### ISSUE TITLE
Throw exception when query does not work

### ISSUE THREAD

**Issue by weierophinney** [mezzio/mezzio-authentication#1]
Throw an exception when we find out that execute() did not work. Since execute() returns false when there is an error we can bubble this up to let the user know their auth roles or auth details query from the config was incorrect.

Provide a narrative description of what you are trying to accomplish:

- [x] Are you fixing a bug?
  - [x] Detail how the bug is invoked currently.
     **If the user puts an incorrect sql query in their auth config it will role over this without telling them it was wrong.**
  - [x] Detail the original, incorrect behavior.
     **If an incorrect sql query is used in the auth config it will show every user has possibly no role or no details**
  - [x] Detail the new, expected behavior.
     **When an incorrect sql query is passed in the config and ran against the db a runtime exception will be thrown showing the details return from errorInfo() on the prepared statement.**
  - [x] Base your feature on the `master` branch, and submit against that branch.

---

Originally posted by @Colmbus72 at https://github.com/zendframework/zend-expressive-authentication/pull/50

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
