### ISSUE TITLE
A new IdentityInterface for authentication

### ISSUE THREAD

**Issue by weierophinney** [mezzio/mezzio-authentication#2]
This PR is a work in progress to solve the issue about OAuth2 client authentication reported in https://github.com/zendframework/zend-expressive-authentication-oauth2/pull/55. The idea is to use a general `IdentityInterface` as follows:

```php
namespace Zend\Expressive\Authentication;

interface IdentityInterface
{
    /**
     * Get the unique identity
     */
    public function getIdentity() : string;
}
```
And a specific `UserInterface` that extends the `IdentityInterface`, as follows:

```php
namespace Zend\Expressive\Authentication;

interface UserInterface extends IdentityInterface
{
    /**
     * Get all user roles
     *
     * @return Iterable
     */
    public function getRoles() : iterable;

    /**
     * Get a detail $name if present, $default otherwise
     */
    public function getDetail(string $name, $default = null);

    /**
     * Get all the details, if any
     */
    public function getDetails() : array;
}
```

Regarding the `AuthenticationMiddleware`, this PR generates a `UserInterface` PSR-7 attribute if `authenticate($request)` returns an instance of `UserInterface`. Otherwise, it will returns a `IdentityInterface` attribute.

These changes *should* prevent BC breaks for existing implementations using `zend-expressive-authentication` and offers a new solution to `zend-expressive-authentication-oauth2` for implementing a `ClientInterface` (extending `IdentityInterface`).

---

Originally posted by @ezimuel at https://github.com/zendframework/zend-expressive-authentication/pull/39

**Comment by weierophinney** [comment]
@ezimuel Is there still work to do on this patch?

---

Originally posted by @weierophinney at https://github.com/zendframework/zend-expressive-authentication/pull/39#issuecomment-469771942

**Comment by weierophinney** [comment]
sorry for the super late response - LGTM 👍 

---

Originally posted by @marc-mabe at https://github.com/zendframework/zend-expressive-authentication/pull/39#issuecomment-474889350

**Comment by weierophinney** [comment]
> @ezimuel Is there still work to do on this patch?

@weierophinney this PR is ready, of course we need to implement a new `ClientInterface` for `zend-expressive-authentication-oauth2` to solve https://github.com/zendframework/zend-expressive-authentication-oauth2/pull/55

---

Originally posted by @ezimuel at https://github.com/zendframework/zend-expressive-authentication/pull/39#issuecomment-475221013

**Comment by weierophinney** [comment]
I've got this and the related one for oauth2 on my todo list - not sure if I'll have time to evaluate them this week, or if it will be early next. I'll drop a note with what route I go (new minor or new major) when I do.

---

Originally posted by @weierophinney at https://github.com/zendframework/zend-expressive-authentication/pull/39#issuecomment-475304879

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
