### ISSUE TITLE
UserInterface::getIdentity() return value

### ISSUE THREAD

**Issue by pine3ree** [mezzio/mezzio-authentication#84]
Should we have a generic/unspecified return value for `UserInterface::getIdentity()`? Or at least `int|string`?

99% of the times I use `integer` ids to persist the authenticated user in the session. Casting to/from `int` all the time is tedious and unelegant. 

Specific implementations can still restrict the return value.
kind regards

**Comment by Ocramius** [comment]
IMO no: for example, I return `UserId` from there in one project 🤔

**Comment by Ocramius** [comment]
Just saying that this is what the authentication layer returns in my system: you can return your own data structure from it. I also have `UserId::system()` for system tasks, for example. 

Also, @wojtekLs, don't save humans: living creatures are not serializable anyway.

**Comment by Ocramius** [comment]
@pine3ree a templated type `T of mixed` would help here, if you can design it, but `int|string` is certainly wrong.

**Comment by pine3ree** [comment]
> @Ocramius Im strongly against `userId`. Users are living creatures, not numbers.

Hello @wojtekLs , 
in fact the authenticated user abstraction could also represents a remote app with an api-key.

As opposed to laminas-auth service getIdentity() method, in mezzio-auth  `getIdentity()` is a method of the actual authenticated user instance.

The matter  I was trying to discuss is the nature of the identity property, the "thing" that uniquely identifies the user and that can be for instance persisted in the session. A `string` identifier is fine, but in my opinion it should be more generic.
Developers  most commonly  utilize`username`(s), `email`(s)...but also storage id(s), (uuids stringd or autoincrement integers). Latest versions of the PDO driver returns `int`(s) for integer db fields by default (unless you instruct it to use the `PDO::ATTR_STRINGIFY_FETCHES` option)
(Technically even arrays and other objects could be used for identification)

kind regards
